### ISSUE TITLE
FastSurfer Code Release?

### ISSUE THREAD

**Issue by jpellman** [Deep-MI/Deep-MI.github.io#19]
At the end of the pre-proof for your [FastSurfer paper](https://www.sciencedirect.com/science/article/pii/S1053811920304985?dgcid=rss_sd_all&utm_source=dlvr.it&utm_medium=twitter#bfn2) you indicate that the FastSurfer codebase will be released upon the paper's acceptance.  On Twitter, there are a few posts that indicate some confusion over this (see [here](https://twitter.com/mripapers/status/1270794246312738817)).  Has the paper not been officially accepted yet?   There seems to be quite a bit of interest in this tool!

**Comment by m-reuter** [comment]
Hi John,Thanks for your interest. We are running final tests and adopt the pipeline to the recently released freesurfer 7.1. Best MartinAm 15.06.2020 00:07 schrieb John Pellman <notifications@github.com>:
At the end of the pre-proof for your FastSurfer paper you indicate that the FastSurfer codebase will be released upon the paper's acceptance.  On Twitter, there are a few posts that indicate some confusion over this (see here).  Has the paper not been officially accepted yet?   There seems to be quite a bit of interest in this tool!
